import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Page } from '@playwright/test';

const here = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(here, '../..');

/** Committed publishable artifacts (updated when maintainers regenerate). */
export const JSON_PATH = path.join(
  repoRoot,
  'docs/benchmarks/marketing-latest.json',
);
export const SNIPPET_PATH = path.join(
  repoRoot,
  'docs/benchmarks/marketing-snippet.md',
);
/** CI / local run copy (gitignored) — never overwrite committed JSON from CI blindly. */
export const RUN_JSON_PATH = path.join(repoRoot, 'marketing-bench-results.json');

export type EngineThroughput = {
  engine: 'worker-sync-db' | 'dexie';
  n: number;
  putMs: number;
  getMs: number;
  queryMs: number;
  putOpsPerSec: number;
  getOpsPerSec: number;
  queryOpsPerSec: number;
  queryCount: number;
};

export type EngineLatency = {
  engine: 'worker-sync-db' | 'dexie';
  n: number;
  putP50Ms: number;
  putP95Ms: number;
  getP50Ms: number;
  getP95Ms: number;
};

export type CrossTabResult = {
  engine: 'worker-sync-db';
  events: number;
  received: number;
  wallMs: number;
  eventsPerSec: number;
};

export type MarketingResults = {
  generatedAt: string;
  environment: {
    browser: string;
    note: string;
  };
  methodology: {
    summary: string;
    comparable: string[];
    notComparable: string[];
  };
  throughput: {
    workerSyncDb: EngineThroughput;
    dexie: EngineThroughput;
  };
  latency: {
    workerSyncDb: EngineLatency;
    dexie: EngineLatency;
  };
  crossTab: CrossTabResult;
};

function round(n: number, digits = 1): number {
  const f = 10 ** digits;
  return Math.round(n * f) / f;
}

function fmtOps(n: number): string {
  if (n >= 1000) return `${round(n / 1000, 2)}k`;
  return String(Math.round(n));
}

function fmtMs(n: number): string {
  return n < 10 ? n.toFixed(2) : n.toFixed(1);
}

export function buildSnippet(results: MarketingResults): string {
  const { throughput: t, latency: l, crossTab: c } = results;
  const w = t.workerSyncDb;
  const d = t.dexie;
  const wl = l.workerSyncDb;
  const dl = l.dexie;

  return `<!-- generated by npm run bench:marketing — do not edit by hand -->
| Workload | worker-sync-db | Dexie (baseline) | Notes |
|----------|----------------:|-----------------:|-------|
| Put throughput (${w.n} sequential) | **${fmtOps(w.putOpsPerSec)} ops/s** | **${fmtOps(d.putOpsPerSec)} ops/s** | Same docs; WSD pays SharedWorker RPC |
| Get throughput (${w.n} sequential) | **${fmtOps(w.getOpsPerSec)} ops/s** | **${fmtOps(d.getOpsPerSec)} ops/s** | Key lookup |
| Put latency p50 / p95 | ${fmtMs(wl.putP50Ms)} / ${fmtMs(wl.putP95Ms)} ms | ${fmtMs(dl.putP50Ms)} / ${fmtMs(dl.putP95Ms)} ms | Single-op samples (n=${wl.n}) |
| Get latency p50 / p95 | ${fmtMs(wl.getP50Ms)} / ${fmtMs(wl.getP95Ms)} ms | ${fmtMs(dl.getP50Ms)} / ${fmtMs(dl.getP95Ms)} ms | Single-op samples (n=${wl.n}) |
| Cross-tab fan-out (${c.events} puts → 2nd tab) | **${fmtOps(c.eventsPerSec)} events/s** (${fmtMs(c.wallMs)} ms wall) | — | Dexie has no SharedWorker multi-tab path |

_Last run: ${results.generatedAt.slice(0, 10)} · ${results.environment.browser}_
`;
}

export function writeArtifacts(
  results: MarketingResults,
  opts: { commitDocs: boolean },
): void {
  const json = JSON.stringify(results, null, 2) + '\n';
  fs.writeFileSync(RUN_JSON_PATH, json);
  // eslint-disable-next-line no-console
  console.info(`[bench:marketing] wrote ${RUN_JSON_PATH}`);

  if (opts.commitDocs) {
    fs.mkdirSync(path.dirname(JSON_PATH), { recursive: true });
    fs.writeFileSync(JSON_PATH, json);
    fs.writeFileSync(SNIPPET_PATH, buildSnippet(results));
    // eslint-disable-next-line no-console
    console.info(`[bench:marketing] wrote ${JSON_PATH}`);
    // eslint-disable-next-line no-console
    console.info(`[bench:marketing] wrote ${SNIPPET_PATH}`);
  }
}

/** Update README Performance table between HTML comment markers. */
export function applyReadmeSnippet(snippet: string): void {
  const readmePath = path.join(repoRoot, 'README.md');
  const readme = fs.readFileSync(readmePath, 'utf8');
  const start = '<!-- marketing-bench:start -->';
  const end = '<!-- marketing-bench:end -->';
  const startIdx = readme.indexOf(start);
  const endIdx = readme.indexOf(end);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    throw new Error(
      'README.md missing <!-- marketing-bench:start/end --> markers',
    );
  }
  const next =
    readme.slice(0, startIdx + start.length) +
    '\n' +
    snippet.trimEnd() +
    '\n' +
    readme.slice(endIdx);
  fs.writeFileSync(readmePath, next);
  // eslint-disable-next-line no-console
  console.info('[bench:marketing] updated README.md Performance table');
}

export async function waitBenchReady(page: Page): Promise<void> {
  await page.waitForFunction(
    () =>
      document.body.dataset.benchReady === '1' &&
      typeof (window as unknown as { __mktBench?: unknown }).__mktBench !==
        'undefined',
    { timeout: 60_000 },
  );
}

export async function benchCall<T>(
  page: Page,
  fn: string,
  ...args: unknown[]
): Promise<T> {
  return page.evaluate(
    async ({ fn, args }) => {
      const api = (
        window as unknown as { __mktBench: Record<string, Function> }
      ).__mktBench;
      return api[fn]!(...args) as T;
    },
    { fn, args },
  );
}

export function roundThroughput(t: EngineThroughput): EngineThroughput {
  return {
    ...t,
    putMs: round(t.putMs, 2),
    getMs: round(t.getMs, 2),
    queryMs: round(t.queryMs, 2),
    putOpsPerSec: Math.round(t.putOpsPerSec),
    getOpsPerSec: Math.round(t.getOpsPerSec),
    queryOpsPerSec: round(t.queryOpsPerSec, 2),
  };
}

export function roundLatency(l: EngineLatency): EngineLatency {
  return {
    ...l,
    putP50Ms: round(l.putP50Ms, 3),
    putP95Ms: round(l.putP95Ms, 3),
    getP50Ms: round(l.getP50Ms, 3),
    getP95Ms: round(l.getP95Ms, 3),
  };
}
